

# Strucutred ouptut using pydantic parser.

import streamlit as st
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel
from typing import List,Optional
from langchain_core.output_parsers import PydanticOutputParser
import os
from dotenv import load_dotenv

load_dotenv()

model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    api_key=os.getenv("GOOGLE_API_KEY")
)

class Movie(BaseModel):
    title:str
    release_yr: Optional[int]
    genre: List[str]
    director: Optional[str]
    cast: List[str]
    rating: Optional[float]
    summary: str

parser = PydanticOutputParser(pydantic_object=Movie)

prompt = ChatPromptTemplate.from_messages([
    ('system',
     """
    extract movie information from the paragraph
    {format_instructions}
"""),
    ('human',
     """    
    {paragraph}
""")    
])

st.title("Movie Summarizer")
st.subheader("Summarise your movie's detailed summary into finest and particular details!")
para = st.text_area("Insert movie paragraph:")


#structured output by pydantic parse
if st.button("Summarize"):
    final_prompt = prompt.invoke(
        {"paragraph": para,
         "format_instructions":parser.get_format_instructions()
    })
    response = model.invoke(final_prompt)

    #structured output by parser, by parsing response.content further
    movie_data = parser.parse(response.content)

    st.subheader("Raw Ouput")
    st.write(response.content)

    st.subheader("Structured Output")
    st.write(movie_data)

    print(response.content)




#     If an interviewer asks:
# "What is structured output in LLMs?"
# A good answer is:
# Structured output is a response generated by an LLM that follows a predefined schema—such as JSON or a Pydantic model—instead of free-form text. This makes the output predictable, machine-readable, and easy to validate and integrate into applications.